version: '2'
services:
  documents:
    image: 'ghacupha/documents:0.0.2-SNAPSHOT'
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://documents-postgresql:5432/documents'
      - JHIPSTER_SLEEP=30
      - 'KAFKA_BOOTSTRAPSERVERS=kafka:9092'
      - 'PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}'
      - 'PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}'
      - 'MAIL_USERNAME=${MAIL_USERNAME}'
      - 'MAIL_PASSWORD=${MAIL_PASSWORD}'
      - 'APP_URL=${APP_URL}'
      - JHIPSTER_REGISTRY_PASSWORD=${JHIPSTER_REGISTRY_PASSWORD}
    ports:
      - '13000:13000'
  documents-postgresql:
    image: 'postgres:12.1'
    volumes:
      - '~/volumes/jhipster/documentsApp/postgresql/:/var/lib/documentsApp/data/'
    environment:
      - 'POSTGRES_USER=${PG_DATABASE_DEV_USER}'
      - 'POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}'
      - POSTGRES_DB=documents

  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
