version: '2'
services:
  documents-app:
    image: ghacupha/documents:0.0.2-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://documents-postgresql:5432/documents
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - APP_URL=${APP_URL} # This is temporary and needs to to be configured on a case by case basis
    ports:
      - 13000:13000
  documents-postgresql:
    extends:
      file: postgresql.yml
      service: documents-postgresql
