version: '2'
services:
  documents-postgresql:
    image: postgres:12.1
    volumes:
      - ~/volumes/documents/documents/postgresql/:/var/lib/documents/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - POSTGRES_DB=documents
    ports:
      - 13001:5432
