export const enum DocumentType {
  CONTRACT = 'CONTRACT',
  LICENSE = 'LICENSE',
  INVOICE = 'INVOICE',
  NOTE = 'NOTE',
  RECEIPT = 'RECEIPT',
  MEMO = 'MEMO',
  TITLE = 'TITLE',
  IDENTITY = 'IDENTITY',
  INSTRUCTION = 'INSTRUCTION'
}
